### ISSUE TITLE
#US07 - Obtener repositorio MiObservador

### ISSUE THREAD

**Issue by adriana43** [PPROF2-2022ProgWeb/g08-aula2-problematicaurbana#8]
Yo usuario adriana43 como nueva integrante del grupo g08 aula2
Quiero interiorizarme, por eso realizo la descarga de los archivos del proyecto problematicaurbana
Para ver lo que esta ya hecho y aportar ideas 

- [crear carpeta en mi pc local para clonar el repositorio ]

**Comment by MaryselR** [comment]
Se clonó repositorio a la PC local.
